workflows:
  ios-build:
    name: iOS Build with Firebase
    environment:
      ruby: 3.2.2
      flutter: stable
      xcode: 15.4
      cocoapods: 1.16.2
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Clean build
        script: |
          flutter clean
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod deintegrate
          pod install
      - name: Clean Xcode cache
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build iOS
        script: flutter build ios --release --no-codesign --no-tree-shake-icons
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - jantabish371@gmail.com
        notify:
          success: true
          failure: true
